apiVersion: v1
kind: ReplicationController
metadata:
    name: elemental-api-rc
spec:
    replicas: 1
    selector:
        app: elemental-api
    template:
        metadata:
            labels:
                app: elemental-api
        spec:
            containers:
            - name: elemental-pod
              image: bonggeek/elementservice:latest
              ports:
              - containerPort: 8080
