apiVersion: v1
kind: Service
metadata:
  name: elemental-svc
  labels:
    app: elemental
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30001
  selector:
    app: elemental-api
